# Generated by Django 6.0.3 on 2026-04-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.TextField()),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement_type', models.CharField(choices=[('Demo', 'Request a Demo'), ('Visit', 'Site Visit'), ('General', 'General Inquiry')], default='General', max_length=50)),
            ],
        ),
    ]
