# Generated by Django 6.0.3 on 2026-04-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Inquiry', 'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='interests',
            field=models.TextField(help_text='Stored as comma-separated values from chips'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='requirement_type',
            field=models.CharField(choices=[('Request a Demo', 'Request a Demo'), ('Site Visit', 'Site Visit'), ('General Inquiry', 'General Inquiry')], default='General Inquiry', max_length=50),
        ),
    ]
