# Generated by Django 6.0.3 on 2026-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0002_alter_contactinquiry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('consulting', 'Consulting'), ('sales', 'Sales & Marketing'), ('support', 'Support')], max_length=50)),
                ('location', models.CharField(default='Thiruvananthapuram, Kerala', max_length=255)),
                ('job_type', models.CharField(default='Full-time', max_length=50)),
                ('work_mode', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Remote / Hybrid', 'Remote / Hybrid')], default='On-site', max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
