# Generated by Django 6.0.3 on 2026-04-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0004_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g., 1 for CEO)')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
