# Generated by Django 6.0.3 on 2026-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
                ('date_text', models.CharField(help_text='Example: April 24, 2026 — 3:00 PM IST', max_length=100)),
                ('description', models.TextField(help_text='A short summary of the event')),
                ('external_link', models.URLField(help_text='LinkedIn URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
